### ISSUE TITLE
Uploading and Generating Not Working :(

### ISSUE THREAD

**Issue by DanielChurch1** [Liam-Fisher/itssomething#2]
The uploading and generating is not working when I upload my clips. I don't know why but it isn't. When I upload a video it says it's uploading and when I was done uploading enough clips I clicked generate and nothing came up

**Comment by DanielChurch1** [comment]
Please fix this issue

**Comment by Liam-Fisher** [comment]
Hi Daniel, 
Sorry I missed your last issue. I just tried and had the same problem but it seems to work now for me now. I had a bunch of random clips uploaded, I'm going to delete them from storage so it will only be your clips. 

Note that you need to upload at least 3 before setting "demo" to "off" and generating a sequence.


Sometimes, the server may throw an error if you are generating new video sequences one after the other. Just give it a few seconds and it should be fine. 

Give it another shot and let me know if it works for you too!

**Comment by DanielChurch1** [comment]
So I followed the instructions you gave me and it worked out great! Could you delete all my clips please because those were for test purposes. The real deal will start next week or maybe later this week. I also want to suggest some changes to the design layout of the website. I have a logo and a background I would like to use for the backdrop of the site. My only gripe is that I think the size of the generator should be bigger and at least fill 50% of the screen. Thank you for making this long lasting dream a reality!
